services:
  # Backend API Service
  - type: web
    name: ai-socratic-seminar-backend
    env: python
    region: ohio
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: FRONTEND_URL
        value: https://siakhorsand.github.io/AI-socratic-seminar
      - key: DEPLOYED_URL
        value: https://siakhorsand.github.io/AI-socratic-seminar
    autoDeploy: true 